# Generated by Django 3.0.5 on 2020-10-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofladding',
            name='declaration',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
