# Generated by Django 3.0.5 on 2020-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0002_billofladding_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofladding',
            name='declaration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
