# Generated by Django 3.0.5 on 2020-10-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bl', '0003_auto_20201026_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofladding',
            name='declaration_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
