# Generated by Django 3.0.7 on 2020-06-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['name'], name='booking_boo_name_d37a99_idx'),
        ),
    ]
