# Generated by Django 3.0.7 on 2020-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200623_0953'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_name_d37a99_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['name'], name='idx_booking_booking_name'),
        ),
    ]
