# Generated by Django 3.0.5 on 2020-11-09 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shorepass.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Booking number')),
                ('terminal', models.CharField(blank=True, choices=[('LCB1', 'LCB1'), ('LCMT', 'LCMT')], max_length=10, null=True)),
                ('vessel_name', models.CharField(max_length=100)),
                ('pod', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='POD does not allow special charecters', regex='^[\\w-]+$')])),
                ('voy', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Voy does not allow special charecters', regex='^[\\w-]+$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('execute_job', models.BooleanField(default=False)),
                ('execute_date', models.DateTimeField(blank=True, null=True)),
                ('execute_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execute_shore', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('verify_shore', 'Can verify shorepass document'), ('execute_shore', 'Can execute shore')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorefile', models.ImageField(blank=True, null=True, upload_to=shorepass.models.image_file_name)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shorepass.Shore')),
            ],
        ),
        migrations.AddIndex(
            model_name='shore',
            index=models.Index(fields=['user'], name='idx_shorepass_shore_user'),
        ),
        migrations.AddIndex(
            model_name='shore',
            index=models.Index(fields=['booking'], name='idx_shorepass_shore_booking'),
        ),
        migrations.AddIndex(
            model_name='shore',
            index=models.Index(fields=['vessel_name'], name='idx_shorepass_shore_vesselname'),
        ),
    ]
