# Generated by Django 3.0.5 on 2020-11-18 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorepass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shore',
            name='customer_name',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer name')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('tax', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shore',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shores', to='shorepass.Customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='idx_shorepass_customer_name'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tax'], name='idx_shorepass_customer_tax'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'tax')},
        ),
    ]
