# Generated by Django 3.0.5 on 2020-11-18 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0002_auto_20201118_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Agent does not allow special charecters', regex='^[\\w-]+$')], verbose_name='Line/Agent name'),
        ),
    ]
