# Generated by Django 3.0.5 on 2020-11-24 01:19

from django.db import migrations, models
import shorepass.models


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0003_auto_20201118_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pod',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='shore',
            name='shorefile1',
            field=models.ImageField(blank=True, null=True, upload_to=shorepass.models.image_shore_file_name),
        ),
        migrations.AddField(
            model_name='shore',
            name='shorefile2',
            field=models.ImageField(blank=True, null=True, upload_to=shorepass.models.image_shore_file_name),
        ),
    ]
