# Generated by Django 3.0.5 on 2020-11-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0003_agent_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='shore',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shores', to='shorepass.Agent'),
        ),
        migrations.AddField(
            model_name='shore',
            name='customer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shore',
            name='pod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shores', to='shorepass.Pod'),
        ),
    ]
