# Generated by Django 3.0.5 on 2020-11-24 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shorepass', '0004_auto_20201124_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='cont_size',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='container',
            name='cont_type',
            field=models.CharField(default='DV', max_length=5),
        ),
        migrations.AddField(
            model_name='container',
            name='container',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='shore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='shorepass.Shore'),
        ),
        migrations.AddField(
            model_name='container',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='container',
            name='stowage',
            field=models.CharField(blank=True, choices=[('UD', 'Underdeck'), ('OD', 'Overdeck')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='temperature',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shorecontainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['container'], name='idx_shore_container_container'),
        ),
    ]
