# Generated by Django 3.0.5 on 2020-11-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0005_auto_20201124_1132'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='container',
            name='idx_shore_container_container',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='container',
            new_name='number',
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['number'], name='idx_shore_container_number'),
        ),
    ]
