# Generated by Django 3.0.5 on 2020-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0006_auto_20201124_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='shore',
            name='containers_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
