# Generated by Django 3.0.5 on 2020-11-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0007_shore_containers_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='shore',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shore',
            name='need_contact',
            field=models.BooleanField(default=False),
        ),
    ]
