# Generated by Django 3.0.5 on 2020-11-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0008_auto_20201125_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='temperature',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
