# Generated by Django 3.0.5 on 2020-11-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorepass', '0009_auto_20201125_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='vent',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
