# Generated by Django 3.0.7 on 2020-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
