# Generated by Django 3.0.7 on 2020-06-22 03:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')])),
                ('ref', models.CharField(max_length=6)),
                ('charge', models.FloatField(default=0)),
                ('vat_rate', models.IntegerField(default=7)),
                ('wht_rate', models.IntegerField(default=3)),
                ('wht', models.BooleanField(default=False)),
                ('grand_total', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to=order.models.image_file_name)),
                ('execute_job', models.BooleanField(default=False)),
                ('execute_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_profile.Address')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='booking.Booking')),
                ('payment_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspect_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('verify_payment', 'Can verify payment'), ('update_payment', 'Can update payment'), ('execute_job', 'Can execute job')],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=15)),
                ('cont_size', models.IntegerField(default=40)),
                ('iso', models.CharField(default='22G1', max_length=10)),
                ('is_oog', models.BooleanField(default=False)),
                ('tariff', models.TextField(blank=True, max_length=300, null=True)),
                ('total', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='order.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
