# Generated by Django 3.0.7 on 2020-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='container_count',
            field=models.IntegerField(default=0),
        ),
    ]
