# Generated by Django 3.0.7 on 2020-06-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_container_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['container'], name='order_conta_contain_3fa5da_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['name'], name='order_order_name_4a638d_idx'),
        ),
    ]
