# Generated by Django 3.0.5 on 2020-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200623_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qrid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
