# Generated by Django 3.0.5 on 2020-10-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200817_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seperate_bill',
            field=models.BooleanField(default=False),
        ),
    ]
