# Generated by Django 3.0.5 on 2020-11-11 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_auto_20201028_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('name', 'user')},
        ),
    ]
