# Generated by Django 3.0.5 on 2020-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20201111_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='invoice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
