# Generated by Django 3.0.5 on 2020-10-26 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orderimport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_profile_phone'),
        ('bl', '0003_auto_20201026_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')])),
                ('ref', models.CharField(max_length=6)),
                ('container_count', models.IntegerField(default=0)),
                ('charge', models.FloatField(default=0)),
                ('vat_rate', models.IntegerField(default=7)),
                ('wht_rate', models.IntegerField(default=3)),
                ('wht', models.BooleanField(default=False)),
                ('grand_total', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to=orderimport.models.image_file_name)),
                ('execute_job', models.BooleanField(default=False)),
                ('execute_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('qrid', models.CharField(blank=True, max_length=30, null=True)),
                ('doc_approved', models.BooleanField(default=False)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('rent', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_orders', to='user_profile.Address')),
                ('bl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bl.BillofLadding')),
                ('payment_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inport_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importorders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('verify_payment', 'Can verify payment'), ('update_payment', 'Can update payment'), ('approve_documemt', 'Can approve document'), ('execute_job', 'Can execute job')],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=15)),
                ('cont_size', models.IntegerField(default=40)),
                ('iso', models.CharField(default='22G1', max_length=10)),
                ('lifton', models.FloatField(default=0)),
                ('relocation', models.FloatField(default=0)),
                ('storage', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='orderimport.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importcontainers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['name'], name='idx_bl_order_name'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['qrid'], name='idx_bl_order_qrid'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['container'], name='idx_bl_container_container'),
        ),
    ]
