# Generated by Django 3.0.5 on 2020-11-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderimport', '0002_auto_20201104_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seperate_bill',
            field=models.BooleanField(default=False),
        ),
    ]
