# Generated by Django 3.0.5 on 2020-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderimport', '0004_auto_20201204_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='invoice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
